# Generated by Django 2.1 on 2018-08-31 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20180831_0513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Croup',
            new_name='Group',
        ),
    ]
