# Generated by Django 2.1 on 2018-09-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exams_name', models.CharField(max_length=256, verbose_name='Іспит')),
                ('exams_date', models.DateField(null=True, verbose_name='Дата та час проведення іспиту')),
                ('professor', models.CharField(max_length=256, verbose_name='Прізвище')),
            ],
            options={
                'verbose_name': 'Іспит',
                'verbose_name_plural': 'Іспити',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='exam',
            field=models.ManyToManyField(to='students.Exam'),
        ),
    ]
