# Generated by Django 2.1 on 2018-09-04 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='exam',
        ),
        migrations.AddField(
            model_name='result',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Exam', verbose_name='Іспит'),
        ),
        migrations.RemoveField(
            model_name='result',
            name='student',
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Student', verbose_name='Студент'),
        ),
    ]
